### ISSUE TITLE
Making Conan mandatory for building hobbits and their packages is barbarism

### ISSUE THREAD

**Issue by KOLANICH** [Mahlet-Inc/hobbits#108]
```
CMake Error at CMakeLists.txt:83 (include):
  include could not find load file:

    /home/KOLANICH/hobbits/build/conanbuildinfo.cmake 
```

**Comment by hello-adam** [comment]
Haha, well played...

I thought Conan made it easier to build hobbits. I work with high school and college students, and I want them to focus on their C++ and software engineering without needing a complete crash course in Linux DevOps/Build Systems.

That being said, I think there's a couple pretty straightforward ways to support non-Conan builds.

1. I (or you? or the wonderful internet CMake stranger reading this?) just need to make the CMake do pretty much what you had before by default, but if a `CONAN_BUILD` (or whatever) flag is set, it will do what I have there now.
2. We can find some way to use the `cmake_find_package` Coann generator (I think I tried to start with that and hit some problem)

**Comment by KOLANICH** [comment]
I have tried your commit.

1. It builds on Ubuntu 21.04. Thanks.
2. But it doesn't find the plugins, likely the plugins path is different in the program and the deb, in the `deb` they are placed into `/usr/plugins` (where `CMAKE_PREFIX` is `usr`), which is clearly violates FHS.
3. It doesn't package Qt Creator wizards and desktop files.

**Comment by hello-adam** [comment]
Ok, looks like 2 and 3 were caused by some missing CMake chunks that got lost in the refactor, so I added them back in and they should be fine.

The wizards aren't a thing anymore (Qt Creator has pretty bad CMake project wizard support at the moment) - I replaced them with cookiecutters which I will probably move to a separate Git repo so that they can be used without actually needing to (explicitly) clone them (I think the repo URL will just need to be in the cookicutter config.)

**Comment by hello-adam** [comment]
I'm pretty sure the build are fine. I haven't tested the deb packages, but I think they should be pretty much like they were before the initial conan stuff.
