### ISSUE TITLE
making a plugin using QtCreator

### ISSUE THREAD

**Issue by Pagalom** [Mahlet-Inc/hobbits#116]
May i miss something but the old way to make a plugin in C was to install wizards like said in the tutorial, but I'm unable to find it.
Is their something i miss ? Did the way to do that improved ? 

I made some researches and [found this](https://github.com/Mahlet-Inc/hobbits/commit/199570f99b9adc1afa87c4e0692b1826a085a465#diff-91139ea71c9fbd3de991e6089d70b462b2bcc4e62d7d9dc52dc6d7a11ce82214), from Adam. But i can't find the file in the Code part.

Can someone help me on this point ?

Thanks !

**Comment by hello-adam** [comment]
Yes, sorry, the video documentation for the plugin development is out of date. I'll probably have some updates in a month or so.

Since transitioning to CMake (vs qmake), I found it was easier to have the plugin templates as "cookiecutters" instead of Qt Creator wizards. Here is the repository with the cookiecutters and instructions on how to use them: https://github.com/Mahlet-Inc/hobbits-cookiecutters

If you wanted to make a plugin within the hobbits project (src/hobbits-plugins/<plugin-type>) like the old wizards, you would use the "core-*" cookiecutters. There are also cookiecutters for python plugins, and for C plugins being developed outside of the hobbits source tree.

I'll leave this issue open for a little bit in case you have any more questions. I want to make it easy to make plugins, so please complain about any difficulties you encounter!

**Comment by Pagalom** [comment]
thanks for your fast response !
i'll try it and come back in 24h to ask my potential questions.

thanks again and see you tomorrow

**Comment by Pagalom** [comment]
hello, sorry i'm late !
I didn't have the time to try it, if you need to close this issue and i need some help, may i open a new one ?

**Comment by hello-adam** [comment]
Yes, feel free to open more issues if you ever have a question or problem.

Since I addressed your initial error, and the required documentation updates fall under the scope of #77 , I'll close this issue.
