### ISSUE TITLE
Should CMake be used for building?

### ISSUE THREAD

**Issue by KOLANICH** [Mahlet-Inc/hobbits#13]

**Comment by hello-adam** [comment]
I found that qmake works fine and integrates well with Qt Creator.  I had a CMake + conan build system that worked well in an internal CI system, but it seemed weird to maintain 2 different build methods. Can you think of a compelling reason to switch to CMake?

**Comment by KOLANICH** [comment]
>Can you think of a compelling reason to switch to CMake?

No. I don't have enough experience with QMake so IDK its drawbacks. I just know that CMake has CPack that can be used to make packages for both RPM and dpkg and Windows, so it'd be easier to package the software if CMake was used.

**Comment by hello-adam** [comment]
OK - I think CMake provides a lot of power and flexibility over qmake, but I don't know that we need any of that at the moment.  I don't think there's a business use-case for packages/installers on our side (the current zipped binaries system is actually a plus to us because it makes it easy to manage multiple "installations"). I'll leave this open for a little while in case anyone else wants to chime in (or volunteer to set up the CMake stuff)

**Comment by hello-adam** [comment]
Cool, that looks like a good start. I guess I need to explain my thought process a little better now:
 1. any changes to this need to retain some compatibility with Qt Creator. I sometimes use this as an educational project for high-schoolers and interns, and I want their setup to be as easy as possible (e.g. install Qt Creator, open hobbits, run it).  Adding a CMake installation to this setup wouldn't be a dealbreaker, but I *do* want to make sure it "just works" in Qt creator without too much of a hassle. I'm pretty sure this can be done with CMake, so this might be a non-issue.
 2. there are wizards that are used for adding new plugins to the project - these would need to be changed to make cmake sub-projects instead of qmake sub-projects (but I'd be willing to do these changes if the other stuff was working)
 3. I don't see where you put the replacement for the versioning stuff, maybe I'm just not looking in the right place
4. The RPATH stuff that lets you run the application in the "portable folder installation" that we're using now probably needs to stay even if we add proper packages and installers because we have users that like the flexibility of that system right now.

1, 2, and maybe 4 might be moot if the CMake stuff is a parallel/alternative build option. As I mentioned I did this before for the CI build, but it felt cumbersome. I don't know, I need some time to think about this (and actually try out what you're working on)

Thank you for the contribution, I think this will be useful in the medium-long-term whether or not I manage to reconcile it with my short-term goals.

**Comment by KOLANICH** [comment]
>any changes to this need to retain some compatibility with Qt Creator.

CMake is the main project format for Qt Creator. The Qt Company has plans to drop QBS in favour of CMake. Qt Creator works fine (I mean it sees them and parses them and analyses them, projects still have to be specified manually in CMake (I mean it's not Visual Studio  where everything is usually done via GUI), but it is not a drawback) with CMake projects AFAIK (though I haven't tested this project for that, concentrating on ). So could you check if this works for you?

>there are wizards that are used for adding new plugins to the project - these would need to be changed to make cmake sub-projects instead of qmake sub-projects (but I'd be willing to do these changes if the other stuff was working)

I have never worked with Qt Creator wizards and IDK how to make a wizard in CMake and if it is possible at all (do I need any Qt Creator headers for it? If I do, it is likely that it cannot be done in CMake currently because Qt Creator still uses QBS (and that's sad, because plugins for it have to use QBS too because of `pri` files needed for that and because to build a plugin I have to download Qt Creator sources instead of a small SDK) ), and TBH I have no plans. Could you fix them yourself?


I am currently interested in the following things about this tool:
1. having this tool being built and packaged easily. I mean I and everyone else should be able to get packages to install into my system easily and fast.
2. Having binary packages generated for each commit. In fact I have an own metabuild and metapackaging system (downloads sources, builds packages and creates distros that can be added into `sources.list` using GitLab CI). It is crucial because once set up it will allow me to stay on bleeding edge without any effort from my side, completely automatically.
3. Separating headers from libs. I mean I should be able to make and test plugins without rebuilding the whole tool.
4. Completely redoing python backend. It is for integrating this tool to Kaitai Struct. It is the final goal. Kaitai Struct is the framework and a DSL for parsing binaries into an AST. But ... I have encountered a [strange format](https://github.com/KOLANICH/kaitai_struct_formats/blob/lto/hardware/GPS/lto.ksy) that I couldn't have completely reversed; I have reversed it to some blocks, but I still don't know what is within these blocks. They look like encrypted/compressed, but I guess they are just tightly packed and sub-byte.
So what I need is
* showing a tree
* being able to analyse each node of type blob in it
* probably highlighting of AST nodes in hex and graphs like in KS Web IDE

So the plan is following:
1. we need a python plugin embedding the interpreter and injecting the API into the interpreter allowing it to modify the state of the app.
2. the interpreter will load my script
3. the script will create a Qt text editor window.
4. the script is going to interact to Kaitai Struct compiler to compile the spec from the text editor using my kaitaiStructCompile lib, transforming the spec into python source
5. the script will eval that source, the result will be called against the blob, the result of that is AST and offsets of boundaries of each block
6. using the API injected by hobhits the script is going to pass this info to hobbits

>I don't see where you put the replacement for the versioning stuff, maybe I'm just not looking in the right place

I haven't touched the versioning stuff, the versions are still weird. I know a CMake script fetching versions from git tags. Should I use it?

>The RPATH stuff that lets you run the application in the "portable folder installation" that we're using now probably needs to stay even if we add proper packages and installers because we have users that like the flexibility of that system right now.

AFAIK CMake does this by default. Could you try?

**Comment by hello-adam** [comment]
> So could you check if this works for you?

Yeah, I will check your copy out later and play around with it a little (maybe I can get it closer to passing the pipelines)

> Could you fix them yourself?

The wizard changes will simply be replacing a .pro file in the template with the cmake file you have in each of the plugins. I can do that when I check out your stuff later today.

>having this tool being built and packaged easily. I mean I and everyone else should be able to get packages to install into my system easily and fast.

I thought the binaries at https://github.com/Mahlet-Inc/hobbits/releases would be fine, but I agree that it would be great if I could just `sudo dnf install hobbits` or whatever.  We did not have a business-case for that, and I have never set something up like that before, *but* I think I could justify some cycles helping someone set it up in the interest of project health.

>Having binary packages generated for each commit. In fact I have an own metabuild and metapackaging system (downloads sources, builds packages and creates distros that can be added into sources.list using GitLab CI). It is crucial because once set up it will allow me to stay on bleeding edge without any effort from my side, completely automatically.

I guess I have everything except the packages/distros/repos part right now.  Do you have any recommendations for how/where to host packages for the various platforms?

>Separating headers from libs. I mean I should be able to make and test plugins without rebuilding the whole tool.

are you referring to having a package for the lib and then a dev/devel package with the headers? I suppose that's the right way to do it.  Again, I have no experience making/maintaining packages, but would be happy to learn.

>Completely redoing python backend

Are you talking about a revamp for the Python Runner plugin?  My initial thought for it was that I could embed the Python interpreter into the plugin itself and make a direct C interface into the Python data structures, but then I got lazy :smile:

I would be super supportive of making the Python plugin better because the current user base likes it.

> integrating this tool to Kaitai Struct.

I need to research kaitai more, but I'm pretty sure that this functionality is one of my goals for the year, so I'm glad to hear you have ideas on how to make it work.

I will get back to you after I do some more research and check out your cmake stuff. I will likely open 1.0 milestone issues for the python runner and kaitai integration by the end of the day

**Comment by KOLANICH** [comment]
>Do you have any recommendations for how/where to host packages for the various platforms?

Not quite. I currently use GitLab CI on gitlab.com for building some packages (pipeline creates a repo, and that repo is available via GitLab Pages because GL pipelines can create GL pages). But I am dissatisfied with 2 things:
1 GitLab is doing bad things and continues doing them. It may make sense to stay away of GitLab.
2 CIs run Turing-complete code, and it cannot be sandboxed reliably. GL CI runs code from anyone. GL uses hw virt to harden the security, but there were multiple vulnrs in various hw virt solutions allowing to compromise the host. Once host is compromised, one can compromise all VMs and infect all the software built in them with malware.
One of the means to reduce probability of this scenario is to build on machines not shared with anyone in the world wishing it. It is not a panacea though: on the same machines other software is built and run, and when done without proper care the code run may be infected. So the ideal variant is a dedicated physical machine.

So, the best variant is to bring it to the official repos and trigger the builds using HTTP hooks. It may make sense to make the pipelines to check the signatures on commits.

>are you referring to having a package for the lib and then a dev/devel package with the headers?

Yeah, but it would require restructuring the repo. I mean separating public headers from private ones.

**Comment by hello-adam** [comment]
I got the build to work in the CI for Linux. I think I need to spend some time with the CPack stuff.

**Comment by KOLANICH** [comment]
Thanks. I confirm that the software now builds.
