### ISSUE TITLE
Embed Python Interpreter in Hobbits Core

### ISSUE THREAD

**Issue by hello-adam** [Mahlet-Inc/hobbits#23]
Having an interpreter inside the Python runner plugin can speed up python processing and might help with other things.

@KOLANICH

**Comment by KOLANICH** [comment]
Moved from https://github.com/Mahlet-Inc/hobbits/issues/13#issuecomment-598418790

>Do you have any recommendations for how/where to host packages for the various platforms?

Not quite. I currently use GitLab CI on gitlab.com for building some packages (pipeline creates a repo, and that repo is available via GitLab Pages because GL pipelines can create GL pages). But I am dissatisfied with 2 things:
1 GitLab is doing bad things and continues doing them. It may make sense to stay away of GitLab.
2 CIs run Turing-complete code, and it cannot be sandboxed reliably. GL CI runs code from anyone. GL uses hw virt to harden the security, but there were multiple vulnrs in various hw virt solutions allowing to compromise the host. Once host is compromised, one can compromise all the VMs and infect all the software built in them with malware.
One of the means to reduce probability of this scenario is to build on machines not shared with anyone in the world wishing it. It is not a panacea though: on the same machines other software is built and run, and when done without proper care the code run may be infected. So the ideal variant is a dedicated physical machine.

So, the best variant is to bring it to the official repos and trigger the builds using HTTP hooks. It may make sense to make the pipelines to check the signatures on commits.

**Comment by hello-adam** [comment]
Updating the scope of this so that a few more general python/hobbits integration possibilities will be available

**Comment by hello-adam** [comment]
I got the embedded interpreter working in the PythonRunner plugin. Now I just need to make it less hacky, get it in the core library, and then figure out how to do the build...

**Comment by hello-adam** [comment]
built-in python has improved and seems to work with the Python Runner and Kaitai Struct plugins

**Comment by hello-adam** [comment]
I'm going to call this done in v0.35.0 - expansion and fine-tuning can be spun out into other issues.
