### ISSUE TITLE
Can you resize rasters?

### ISSUE THREAD

**Issue by Aang23** [Mahlet-Inc/hobbits#57]
So I was wonder if there is any way to just set the width of bit / bytes rasters / etc without performing any framing work.
The width framer messes it up and so I have to attach a sync marker and do it that way...

![Screenshot from 2020-07-23 12-46-57](https://user-images.githubusercontent.com/23421917/88278881-6d342d80-cce3-11ea-903f-045a370f6858.png)
With Width Framer

![Screenshot from 2020-07-23 12-48-19](https://user-images.githubusercontent.com/23421917/88278928-8210c100-cce3-11ea-9c62-bec37a44b873.png)
Using added sync markers

**Comment by hello-adam** [comment]
The width framer shouldn't be changing the data at all. Is it changing the data, or just guessing the wrong width? You can manually set the width in the width framer if the guess is bad.

Since the width framer isn't supposed to change the data, it *should* be doing the equivalent of the "set raster width" that you describe. If it isn't doing that, it's a bug. Can you explain the steps you take to get the good and bad result more closely? Can you share the data?

**Comment by hello-adam** [comment]
@Aang23 did I answer your question? is it still confusing? did I misunderstand?

**Comment by hello-adam** [comment]
@Aang23 I'm still curious about this in case there's something I could be fixing in the autocorrelation or the width framer. I'll probably close this if I don't hear back soon though

**Comment by hello-adam** [comment]
closing for now
